
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budgeteer-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <your-git-repo-url>
    path: apps/budgeteer-server
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
