apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budgeteer-backend
  namespace: argocd
spec:
  project: budgeteer
  source:
    repoURL: https://github.com/sammosios/gitops-project.git
    path: apps/server/base
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: budgeteer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true